import os
import subprocess
import shutil


node_cleaning= f"python normalization.py"
subgraphs3= f"python subgraph3.py"
subgraphs1= f"python subgraph1.py"
subgraphs2= f"python subgraph2.py"
graph2vec = f"python graph2vec.py"
extract_input=f"python extract_input_rnn.py"
separe_test=f"python separe_test.py"
rnn=f"python rnn.py"


try:
    print("node cleaning")
    subprocess.run(node_cleaning, shell=True, check=True)
    print("subgraphs")
    os.mkdir("subgraphs")
    print("mask 1")
    subprocess.run(subgraphs1, shell=True, check=True)
    print("mask 2")
    subprocess.run(subgraphs2, shell=True, check=True)
    print("mask 3")
    subprocess.run(subgraphs3, shell=True, check=True)
    shutil.rmtree("dataset_cfg_json_normalize")
    print("graph2vec")
    subprocess.run(graph2vec, shell=True, check=True)
    shutil.rmtree("subgraphs") 
    print("extract_input_rnn")
    subprocess.run(extract_input, shell=True, check=True)
    print("separe_test")
    subprocess.run(separe_test, shell=True, check=True)
    shutil.rmtree("input_rnn")
    print("vulnerability detection")
    subprocess.run(rnn, shell=True, check=True)
    shutil.rmtree("test_rnn")
    shutil.rmtree("train_rnn")
    
except subprocess.CalledProcessError as e:
    print(f"Erreur lors de l'ex√©cution de la commande : {e}") 